### ISSUE TITLE
Run list media on other isolate or (Thread)

### ISSUE THREAD

**Issue by alishe79** [Firelands128/photo_gallery#45]
Hello dear @Firelands128 
i have a problem with this plugin.

this is my code 
```dart
ReceivePort p = ReceivePort();
p.listen((message) {
    // other codes
});
Isolate.spawn(loadContents, [p.sendPort, album, files.length]);
```

this is load content function.
```dart
Future<List?> loadContents(List<Object> arguments) async {
  SendPort p = arguments[0] as SendPort;
  Album album = arguments[1] as Album;
  int length = arguments[2] as int;
  var listAlbum = await album.listMedia(
      skip: length,
      take: 21,
      newest: true
  );
  Isolate.exit(p, listAlbum);
}```
```
when run this app see this error message in console.
```
`
E/flutter (12023): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: Invalid argument(s): Illegal argument in isolate message: (object extends NativeWrapper - Library:'dart:ui' Class: Path)
E/flutter (12023): #0      Isolate._spawnFunction (dart:isolate-patch/isolate_patch.dart:399:25)
E/flutter (12023): #1      Isolate.spawn (dart:isolate-patch/isolate_patch.dart:379:7)
E/flutter (12023): #2      NavigationViewModel.addImagesInDatabase (package:smart_gallery/provider/notifier/navigation_viewmodel.dart:145:13)
E/flutter (12023): <asynchronous suspension>
`
```
i have a question !
how i can use listMedia function in flutter isolate ?
Thank's in advance!
```

**Comment by renanzdm** [comment]
the dart:ui native library cannot run on an isolate

**Comment by Firelands128** [comment]
Close the issue, because @renanzdm said it absolutely right.
